/* Copyright 2021 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef METAL__DRIVERS__SIFIVE_MALLARD0_H
#define METAL__DRIVERS__SIFIVE_MALLARD0_H

#ifdef METAL_SIFIVE_MALLARD0

#include <metal/mallard.h>

/* MALLARD TwinJet Control Register */

/* Offset of bit field in HWPFCSR Register */
#define HWPF1CSR_ENABLE_OFFSET 0
#define HWPF1CSR_WINDOW_OFFSET 1
#define HWPF1CSR_DIST_OFFSET                                                   \
    (HWPF1CSR_WINDOW_OFFSET + METAL_MALLARD0_TWINJET_WINDOWBITS)
#define HWPF1CSR_MAXALLOWEDDIST_OFFSET                                         \
    (HWPF1CSR_DIST_OFFSET + METAL_MALLARD0_TWINJET_DISTANCEBITS)
#define HWPF1CSR_LINTOEXPTHRD_OFFSET                                           \
    (HWPF1CSR_MAXALLOWEDDIST_OFFSET + METAL_MALLARD0_TWINJET_DISTANCEBITS)
#define HWPF1CSR_QFULLNESSTHRDL1_OFFSET                                        \
    (HWPF1CSR_LINTOEXPTHRD_OFFSET + METAL_MALLARD0_TWINJET_DISTANCEBITS)
#define HWPF1CSR_HITCACHETHRDL1_OFFSET                                         \
    (HWPF1CSR_QFULLNESSTHRDL1_OFFSET + METAL_MALLARD0_TWINJET_QFULLNESSTHRDBITS)
#define HWPF1CSR_HITMSHRTHRDL1_OFFSET                                          \
    (HWPF1CSR_HITCACHETHRDL1_OFFSET + METAL_MALLARD0_TWINJET_HITCACHETHRDBITS)
#define HWPF1CSR_ISSUEBUBBLE_OFFSET                                            \
    (HWPF1CSR_HITMSHRTHRDL1_OFFSET + METAL_MALLARD0_TWINJET_HITMSHRTHRDBITS)
#define HWPF1CSR_MAXL1PFDIST_OFFSET (HWPF1CSR_ISSUEBUBBLE_OFFSET + 1)
#define HWPF1CSR_FORGIVETHRD_OFFSET                                            \
    (HWPF1CSR_MAXL1PFDIST_OFFSET + METAL_MALLARD0_TWINJET_DISTANCEBITS)
#define HWPF1CSR_NUML1PFLSSQENT_OFFSET (HWPF1CSR_FORGIVETHRD_OFFSET + 2)

/* Offset of bit field in HWPF2CSR Register */
#define HWPF2CSR_L2PFENABLE_OFFSET 0
#define HWPF2CSR_QFULLNESSTHRDL2_OFFSET 1
#define HWPF2CSR_HITCACHETHRDL2_OFFSET                                         \
    (HWPF2CSR_QFULLNESSTHRDL2_OFFSET + METAL_MALLARD0_TWINJET_QFULLNESSTHRDBITS)
#define HWPF2CSR_HITMSHRTHRDL2_OFFSET                                          \
    (HWPF2CSR_HITCACHETHRDL2_OFFSET + METAL_MALLARD0_TWINJET_HITCACHETHRDBITS)
#define HWPF2CSR_NUML2PFLSSQENT_OFFSET                                         \
    (HWPF2CSR_HITMSHRTHRDL2_OFFSET + METAL_MALLARD0_TWINJET_HITMSHRTHRDBITS)

#define HWPFCSR_ENABLE_MASK (1 << HWPF1CSR_ENABLE_OFFSET)

/* Suggested value for MALLARD */
#define MALLARD_HWPF1CSR_ENABLE 0x1UL
#define MALLARD_HWPF1CSR_WINDOW 0x20UL
#define MALLARD_HWPF1CSR_DIST 0x4UL
#define MALLARD_HWPF1CSR_MAXALLOWEDDIST 0x3FUL
#define MALLARD_HWPF1CSR_LINTOEXPTHRD 0x3UL
#define MALLARD_HWPF1CSR_QFULLNESSTHRDL1 0xEUL
#define MALLARD_HWPF1CSR_HITCACHETHRDL1 0xAUL
#define MALLARD_HWPF1CSR_HITMSHRTHRDL1 0x2UL
#define MALLARD_HWPF1CSR_ISSUEBUBBLE 0x0UL
#define MALLARD_HWPF1CSR_MAXL1PFDIST 0x8UL
#define MALLARD_HWPF1CSR_FORGIVETHRD 0x0UL
#define MALLARD_HWPF1CSR_NUML1PFLSSQENT 0x2UL

#define MALLARD_HWPF2CSR_L2PFENABLE 0x1UL
#define MALLARD_HWPF2CSR_QFULLNESSTHRDL2 0xFUL
#define MALLARD_HWPF2CSR_HITCACHETHRDL2 0x14UL
#define MALLARD_HWPF2CSR_HITMSHRTHRDL2 0x4UL
#define MALLARD_HWPF2CSR_NUML2PFLSSQENT 0x2UL

/* CSR numbers */
#define CSR_HWPF1CSR 0x7c3
#define CSR_HWPF2CSR 0x7c4

void sifive_mallard0_init(void);

#endif

#endif /* METAL__DRIVERS__SIFIVE_MALLARD0_H */
