#!/bin/bash -x

set -e

if [ "$#" -ne 5 ]; then
  echo "Illegal number of parameters" >&2
  exit 1
fi

host=$1
machine_header=$2
machine_inline=$3
platform_header=$4
install_dir=$5

machine_header=$(pwd)/$machine_header
machine_inline=$(pwd)/$machine_inline
platform_header=$(pwd)/$platform_header
install_dir=$(pwd)/${install_dir}

export RISCV_PATH=$RISCV

./configure \
  --host=$host \
  --with-builtin-libgloss \
  --with-machine-name=$machine_name \
  --with-machine-header=$machine_header \
  --with-machine-inline=$machine_inline \
  --with-platform-header=$platform_header \
  --prefix=
make \
  RANLIB="riscv64-unknown-elf-ranlib -D" \
  ARFLAGS=Dcr
make  \
  RANLIB="riscv64-unknown-elf-ranlib -D" \
  ARFLAGS=Dcr \
  DESTDIR=$install_dir \
  install
